#!/usr/bin/env python3
"""Generate src/rt/nid_names.h: a NID -> PSP function-name table.

Source of truth is PPSSPP's own HLE function tables (third_party/ppsspp/Core/HLE/*.cpp),
whose entries look like:  { 0XCA04A2B9, &WrapU_U<...>, "sceKernelRegisterSubIntrHandler", ... }

The table is consulted only on the rare unknown/unimplemented-NID path (src/rt/hle.c) so a
missing import names itself instead of printing bare hex. See RENDERING.md section 7.

Usage:  python tools/gen_nidnames.py
"""
import re
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENTRY = re.compile(r'\{\s*0[xX]([0-9A-Fa-f]{8})\s*,[^,]*,\s*"([^"]+)"')


def main():
    names = {}
    for f in glob.glob(os.path.join(ROOT, "third_party/ppsspp/Core/HLE/*.cpp")):
        with open(f, encoding="utf-8", errors="ignore") as fh:
            txt = fh.read()
        for m in ENTRY.finditer(txt):
            names.setdefault(int(m.group(1), 16), m.group(2))

    items = sorted(names.items())
    lines = [
        "/* NID -> PSP function name table. AUTO-GENERATED by tools/gen_nidnames.py from",
        " * PPSSPP's HLE function tables (third_party/ppsspp/Core/HLE/*.cpp). Do not edit by hand.",
        " * Consulted only on the rare unknown/unimplemented-NID path so a missing import names",
        " * itself instead of printing bare hex. See RENDERING.md section 7. */",
        "#ifndef SR_NID_NAMES_H",
        "#define SR_NID_NAMES_H",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "typedef struct { uint32_t nid; const char *name; } SrNidName;",
        "/* Sorted ascending by nid for binary search. */",
        "static const SrNidName sr_nid_table[] = {",
    ]
    for nid, nm in items:
        nm = nm.replace("\\", "\\\\").replace('"', '\\"')
        lines.append('    {0x%08xu, "%s"},' % (nid, nm))
    lines.append("};")
    lines.append("static const size_t sr_nid_table_count = "
                 "sizeof(sr_nid_table)/sizeof(sr_nid_table[0]);")
    lines.append("")
    lines.append("/* Returns the PSP function name for a NID, or NULL if unknown. */")
    lines.append("static inline const char *sr_nid_name(uint32_t nid) {")
    lines.append("    size_t lo = 0, hi = sr_nid_table_count;")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + (hi - lo) / 2;")
    lines.append("        uint32_t m = sr_nid_table[mid].nid;")
    lines.append("        if (m == nid) return sr_nid_table[mid].name;")
    lines.append("        if (m < nid) lo = mid + 1; else hi = mid;")
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* SR_NID_NAMES_H */")

    out = os.path.join(ROOT, "src/rt/nid_names.h")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s with %d entries" % (out, len(items)))


if __name__ == "__main__":
    main()
