#!/usr/bin/env python3
# Differential-fuzz generator for the VFPU codegen. Scans the ELF's executable ranges for
# every DISTINCT VFPU compute instruction word, translates each with codegen.vfpu_effect
# (exactly what acx_recomp.c contains), and emits build/acx/vfpu_fuzz_cases.h:
#     a table {word, sample_addr} and a switch running the generated C for case i.
# src/rt/vfpu_fuzz.c runs each case against sr_vfpu_interp on randomized states.
#
# Usage: vfpu_fuzz_gen.py <elf> <out.h> [--base=HEX]

import sys

from analyze import Elf, exec_ranges
import codegen

VFPU_COMPUTE_OPS = {0x18, 0x19, 0x1B, 0x34, 0x37, 0x3C}  # 0x37 = vpfx (STATE) + viim/vfim


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    opts = [a for a in argv[1:] if a.startswith("--")]
    if len(args) < 2:
        sys.stderr.write("usage: vfpu_fuzz_gen.py <elf> <out.h> [--base=HEX]\n")
        return 2
    base = None
    for o in opts:
        if o.startswith("--base="):
            base = int(o.split("=", 1)[1], 16)
    elf = Elf(args[0], base=base)
    ranges = exec_ranges(elf)

    seen = {}
    for lo, hi in ranges:
        a = lo
        while a + 4 <= hi:
            w = codegen.read32(elf, a)
            a += 4
            if w is None:
                continue
            if (w >> 26) in VFPU_COMPUTE_OPS and w not in seen:
                seen[w] = a - 4

    cases = []
    skipped = 0
    for w, addr in sorted(seen.items()):
        try:
            body, _, _ = codegen.vfpu_effect(addr, w)
        except codegen.Unsupported as e:
            sys.stderr.write(f"skip (codegen Unsupported): {e}\n")
            skipped += 1
            continue
        cases.append((w, addr, body))

    out = ["/* Generated by tools/vfpu_fuzz_gen.py. Do not edit. */", ""]
    out.append(f"#define FUZZ_NCASES {len(cases)}")
    out.append("static const struct { uint32_t w, addr; } fuzz_cases[FUZZ_NCASES] = {")
    for w, addr, _ in cases:
        out.append(f"    {{0x{w:08x}u, 0x{addr:08x}u}},")
    out.append("};")
    out.append("")
    out.append("static void fuzz_run_codegen(CpuState *s, int idx) {")
    out.append("    switch (idx) {")
    for i, (w, addr, body) in enumerate(cases):
        out.append(f"    case {i}: /* 0x{w:08x} @0x{addr:08x} */ {body} break;")
    out.append("    default: break;")
    out.append("    }")
    out.append("}")
    out.append("")
    with open(args[1], "w") as f:
        f.write("\n".join(out))
    sys.stderr.write(f"vfpu_fuzz_gen: {len(cases)} distinct VFPU compute words ({skipped} skipped)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
